### ISSUE TITLE
feat:初次使用的一點建议

### ISSUE THREAD

**Issue by Tim0x0** [zsjy/halo-theme-dream2.0-plus#204]
### 你当前使用的 Halo 版本

 2.20.21

### 你当前使用的 Dream 版本

 1.6.0

### 描述一下此特性

首页
标题栏最左侧站点信息是否能添加隐藏

文章设置
开启网格模式会出现文章重复显示（上面几条文章是默认模式，下面又出现网格模式，不知道是不是哪里设置不对）

瞬间
可否取消左右栏目，只显示内容栏

**Comment by mjsoftking** [comment]
1. 注入CSS
``` css
.navbar .logo-title {
  display: none;
}
```
2. 网格模式要求文章必须配置缩略图，也可以在 `文章设置 - 默认文章封面图` 设置默认封面图
3. 不考虑
