### ISSUE TITLE
bug:halo用的这个主题和maxkb无法同时使用，主题的按钮会遮挡住maxlb。

### ISSUE THREAD

**Issue by wshlyl** [zsjy/halo-theme-dream2.0-plus#33]
### 使用的 Dream 版本是多少？

1.3.2

### 在线博客地址

https://halo.ntsc.fun

### BUG 内容

大佬，halo用的这个主题和maxkb无法同时使用，主题的按钮会遮挡住maxlb，换了浏览器也是这种情况。我看官网的宏尘极客的网站是正常的，请教下怎么设置。
![image](https://github.com/user-attachments/assets/e8d744c6-566a-4bb9-8e06-2850f1489936)

**Comment by mjsoftking** [comment]
``` css
#maxkb .maxkb-chat-button {
    bottom: 0px !important;
    right: 8px !important;
    z-index: 500 !important;
  }

  @media (max-width: 768px) {
    #maxkb .maxkb-chat-button {
        display: none !important;
    }
}

.actions {
    bottom: 60px !important;
}

```

![image](https://github.com/user-attachments/assets/9e16e335-c483-42ad-b6dc-2a8544706cbf)
添加上述代码，控制位置
