### ISSUE TITLE
feat: 代码换行

### ISSUE THREAD

**Issue by yss930819** [zsjy/halo-theme-dream2.0-plus#56]
### 你当前使用的 Halo 版本

2.20.0

### 你当前使用的 Dream 版本

1.3.9

### 描述一下此特性

希望能增加代码块的换行功能。

有些代码太长会超出边界。

![Image](https://github.com/user-attachments/assets/4b32a9e3-9ce9-487a-92fd-ab03ec65faa1)

**Comment by mjsoftking** [comment]
不支持，建议写文章代码时手动换行

**Comment by mjsoftking** [comment]
``` css
figure code {
    /* 允许长单词换行 */
  word-wrap: break-word; /* 旧属性 */
  overflow-wrap: break-word; /* 新标准属性 */
  
  /* 保留换行符，允许文本自然换行 */
  white-space: pre-wrap;
  
  /* 禁止文本溢出容器 */
  overflow: hidden;
}
```

注入css可以做到，但是行号就会无法计算，因此不考虑实现此功能
